# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Ther-nullptr"
repo_name: "circult-eda-mlsys-tinyml-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False
update_paper_links: True

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Quantization":
        filters: ["Post Training Quantization", "Quantization Aware Training"]
    "Pruning":
        filters: ["Structured Pruning", "Unstructured Pruning"]
    "Hardware-Software Co-Design":
        filters: ["Hardware Software Codesign", "Hardware Accelerator", "AI Compiler"]
    "TinyML":
        filters: ["TinyML", "Edge AI", "Embedded AI"]
    "Domain Specific Accelerator":
        filters: ["Domain Specific Accelerator", "DNN Accelerator", "AI Chip"]
    "Low-Rank Adaptation":
        filters: ["LoRA", "Low Rank Adaptation"]
    "Model Compression":
        filters: ["Model Compression", "Knowledge Distillation", "Model Pruning"]
